# Generated by Django 5.0.6 on 2024-05-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_departments',
            field=models.IntegerField(default=0, verbose_name='Number of departments'),
        ),
        migrations.AlterField(
            model_name='department',
            name='number_of_employees',
            field=models.IntegerField(default=0, verbose_name='Number of Employees'),
        ),
    ]
