# Generated by Django 5.0.6 on 2024-05-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_number_of_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(default=0, verbose_name='Number of Employees'),
        ),
    ]
