# Generated by Django 5.0.6 on 2024-05-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_days_employed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
