# Generated by Django 5.0.6 on 2024-05-28 00:30

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_initial'),
        ('employee', '0004_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Application Received', 'Application Received'), ('Interview Scheduled', 'Interview Scheduled'), ('Hired', 'Hired'), ('Not Accepted', 'Not Accepted')], default='Application Received', max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100, verbose_name='Designation (Position/Title)')),
                ('hired_on', models.DateField(blank=True, null=True)),
                ('days_employed', models.DateField(blank=True, null=True, verbose_name='Days Empolyed')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_employee', to='company.department')),
            ],
        ),
    ]
