# Generated by Django 5.0.6 on 2024-05-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('number_of_departments', models.IntegerField(verbose_name='Number of departments')),
                ('number_of_employees', models.IntegerField(verbose_name='Number of Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('number_of_employees', models.IntegerField(verbose_name='number_of_employees')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_company', to='company.company')),
            ],
        ),
    ]
