# Generated by Django 5.0.6 on 2024-05-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='days_employed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days Empolyed'),
        ),
    ]
