# Generated by Django 5.0.6 on 2024-05-28 03:46

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_days_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
