# Generated by Django 5.0.6 on 2024-05-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_number_of_employees'),
        ('employee', '0007_alter_employee_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_employee', to='company.department'),
        ),
    ]
